[package]
name = "hls-fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
hls-parse = { path = "../hls-parse" }
reqwest = { version = "0.12.15", features = ["blocking"] }
